name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  persian_datetime_picker:
    path : ../
 
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  fonts:
    - family: IranYekan
      fonts:
        - asset: assets/fonts/IRANYekanMobileLight.ttf
          weight: 200
        - asset: assets/fonts/IRANYekanMobileRegular.ttf
          weight: 200 
