name: persian_datetime_picker
description: A persian (farsi,shamsi) datetime picker for flutter, inspired by material datetime picker.
version: 0.0.1
author: Mohammad amir mohammdi <mem.amir.m@gamil.com>
homepage: https://github.com/M-amir-M/persian-datetime-picker

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shamsi_date: ^0.5.5
  flushbar: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: is
      fonts: 
        - asset:  assets/fonts/IRANSans.ttf
