name: persian_datetime_picker
description: A persian (farsi,shamsi,jalali) datetime picker for flutter, inspired by material datetime picker.
version: 3.0.1

homepage: https://github.com/M-amir-M/persian-datetime-picker

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shamsi_date: ^1.0.4


dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:

