name: persian_datetime_picker
description: A persian (farsi,shamsi,jalali) datetime picker for flutter, inspired by material datetime picker.
version: 3.1.0

homepage: https://github.com/M-amir-M/persian-datetime-picker

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shamsi_date: ^1.0.4


dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:

